name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_tox:
    name: tox -e ${{ matrix.toxenv }} (${{ matrix.python-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
        os:
          - "ubuntu-20.04"
        toxenv:
          - "py38"
          - "py39"
          - "py310"
        include:
          - python-version: "3.8"
            os: "ubuntu-20.04"
            toxenv: "py38"
          - python-version: "3.9"
            os: "ubuntu-20.04"
            toxenv: "py39"
          - python-version: "3.10"
            os: "ubuntu-20.04"
            toxenv: "py310"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U coverage setuptools tox wheel
          python --version
          pip --version
          tox --version
          coverage --version

      - name: Run tests
        run: tox -e ${{ matrix.toxenv }}
